math(EXPR a 10*10 OUTPUT_FORMAT DECIMAL) # a = 100
math(EXPR b "0x7FFFFFFFFFFFFFFF + 0x7FFFFFFFFFFFFFFF") # b = -2
math(EXPR c "16" OUTPUT_FORMAT HEXADECIMAL) # c = 0x10
math(EXPR d "~16" OUTPUT_FORMAT HEXADECIMAL) # d = 0xffffffffffffffef
# math(EXPR err "0xFFFFFFFFFFFFFFFF")